### ISSUE TITLE
Create a document to explain web platform async timing entry-points

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/spec-reviews#100] opened 2016-01-13 01:30 UTC
As discussed at Melbourne F2F, there are a lot of ways in the platform to schedule stuff, and lots of APIs that do it.

We would like to create a document that collates all of these timing entry-points, describes where the timings should happen in relation to other implementation details (layout, painting), and applies fixes for known issues (as noted by @dbaron) with HTML5 task queue description.

**Comment by dbaron** [comment] 2016-01-13 02:58
https://lists.w3.org/Archives/Public/public-houdini/2015Oct/0017.html was the discussion we had in Paris at the Houdini meeting in august, which covers mostly improvements to the rendering part.

This is related to, but somewhat distinct, from the idea of having all of these different task queues (setTimeout, microtask, nanotask, setImmediate, setIdleCallback, etc.) and perhaps the need for a better developer-facing way to prioritize tasks.

**Comment by domenic** [comment] 2016-01-13 03:23
I'm a little unclear on the scope here. Maybe the minutes would make it clearer?

> describes where the timings should happen in relation to other implementation details (layout, painting), and applies fixes for known issues (as noted by @dbaron) with HTML5 task queue description.

This sounds like it would be best done not as a separate document but as a pull request to modify https://html.spec.whatwg.org/#processing-model-8.

> We would like to create a document that collates all of these timing entry-points

This might be a worthwhile guidance document explaining when and how specs should use HTML's algorithms to perform their work.

> perhaps the need for a better developer-facing way to prioritize tasks.

There are actually some discussions on this happening right now between myself and the Angular team. We hope to send a proposal as an issue on whatwg/html shortly (next few days probably). Stay tuned!

**Comment by dbaron** [comment] 2016-01-13 03:30
> This sounds like it would be best done not as a separate document but as a pull request to modify https://html.spec.whatwg.org/#processing-model-8.

Yeah, I agree this probably doesn't belong in a TAG document, although the plan in the Houdini group was to write a separate rendering pipeline document, and presumably then make a pull request to change a few of the list items in the HTML spec's event loop description to refer to an entirely separate (and probably substantially larger) spec.

**Comment by domenic** [comment] 2016-01-13 03:38
> although the plan in the Houdini group was to write a separate rendering pipeline document, and presumably then make a pull request to change a few of the list items in the HTML spec's event loop description to refer to an entirely separate (and probably substantially larger) spec.

That makes a lot of sense to me; I agree that HTML's "update the rendering" (step 7) would largely best be handled by the CSSWG.

**Comment by plinss** [comment] 2016-01-13 05:31
Dupe of issue #72

**Closed by plinss** 2016-01-13 05:31 UTC
Labels: duplicate
